export const PROJECTS_DATA = [
  {
    id: 1,
    名稱: "淡江資傳畢業展-在句點之前",
    擔任職務: ["專案管理", "活動企劃"],
    開始: 2021,
    結束: 2022,
    類型: "校園案",
    工具: ["Figma", "Asana"],
    程式: "",
    描述: "策辦一場長達一年並管理100人的畢業展覽活動。",
    圖片: "/Doting.jpg", // 放在 public/images 下
    連結: "https://www.instagram.com/dot__ing/",
    狀態: true
  },
  {
    id: 2,
    名稱: "未來科技館-官方網站改版",
    擔任職務: ["專案管理"],
    開始: 2022,
    結束: 2023,
    類型: "政府案",
    工具: ["Figma","Redmine","jenkins"],
    程式: "",
    描述: "為未來科技館重新改版展示每年獲獎隊伍資訊的平台。",
    圖片: "/futex.jpg",
    連結: "https://www.futuretech.org.tw/futuretech/index.php",
    狀態: true
  },
  {
    id: 3,
    名稱: "統一資訊-B2B2C店商平台開發",
    擔任職務: ["專案管理"],
    開始: 2022,
    結束: 2024,
    類型: "企業案",
    工具: ["Figma","Redmine","jenkins","github"],
    程式: "",
    描述: "為統一集團開發一款「電子商務平台」，讓消費者能夠同時擔任賣家及買家的角色。",
    圖片: "/iopenmall.png",
    連結: "https://mall.iopenmall.tw/iopen/",
    狀態: true
  },
  {
    id: 4,
    名稱: "桃園市政府-觀光遊程網站開發",
    擔任職務: ["專案管理"],
    開始: 2024,
    結束: 2024,
    類型: "政府案",
    工具: ["Figma", "Redmine","jenkins"],
    程式: "",
    描述: "主要提供官方平台的功能及後台資料上傳；同步提供集點活動及刮刮樂活動。",
    圖片: "/taoyuanfarm.png",
    連結: "https://tyfarm.tycg.gov.tw/tyfarm/",
    狀態: true
  },
  {
    id: 5,
    名稱: "桃園養工處-橋梁監控平台改版",
    擔任職務: ["前端工程師","專案管理"],
    開始: 2024,
    結束: 2025,
    類型: "政府案",
    工具: ["Figma","React","Vite","leaflet","rechart","redux","contextAPI","Axios","Github","Gitlab","GoogleCloud"],
    程式: ["JS","CSS"],
    描述: "取得 2025精品獎、入圍 2025AI創新大賞；本平台針對加速規震動數據進行蒐集和演算，推測橋梁此刻的穩定程度。",
    圖片: "/images/project4.jpg",
    連結: "/TYbridge",
    狀態: true
  },
  {
    id: 6,
    名稱: "福記-蛋煮制製成率預測平台開發",
    擔任職務: ["前端工程師"],
    開始: 2024,
    結束: 2025,
    類型: "企業案",
    工具: ["Figma","jQuery","Ajax","Gitlab"],
    程式: ["html","JS","CSS"],
    描述: "開發一個預測蛋製成率的平台；透過模型及蒐集到的場面數據推算出蛋的熟度。",
    圖片: "/images/project4.jpg",
    連結: "#",
    狀態: true
  },
  {
    id: 7,
    名稱: "高雄台創-橋梁監控平台開發",
    擔任職務: ["前端工程師","專案管理"],
    開始: 2025,
    結束: 2025,
    類型: "企業案",
    工具: ["Figma","React","Vite","rechart","redux","Axios","Gitlab"],
    程式: ["JS","CSS"],
    描述: "為客戶開發一套橋梁資料管理系統；提供資料上傳和紀錄的功能。",
    圖片: "/images/project4.jpg",
    連結: "#",
    狀態: true
  },
  {
    id: 8,
    名稱: "政府-航空器安全降落辨識系統",
    擔任職務: ["前端工程師"],
    開始: 2024,
    結束: 2025,
    類型: "政府案",
    工具: ["Figma","React","Vite","webRTC","webSocket","rechart","redux","Axios","Nginx","Gitlab"],
    程式: ["JS","CSS"],
    描述: "針對航空降落任務安全相關的AI專案；提供即時影像及即時辨識功能。",
    圖片: "/images/project4.jpg",
    連結: "#",
    狀態: true
  },
  {
    id: 9,
    名稱: "政府-靶場觀測計分系統",
    擔任職務: ["前端工程師"],
    開始: 2024,
    結束: 2025,
    類型: "政府案",
    工具: ["Figma","React","Vite","webRTC","webSocket","rechart","redux","Axios","Nginx","Gitlab"],
    程式: ["JS","CSS"],
    描述: "針對打靶積分進行觀測相關的AI專案；提供即時影像及即時辨識功能。",
    圖片: "/images/project4.jpg",
    連結: "#",
    狀態: false
  },
];